---
title: "Final Project"
author: "Team"
output: html_document
---

# Issues:

> Need to set up a loop to append every 20 results

> May need to flatten dataframe


```{r}
suppressMessages(suppressWarnings(library(knitr)))
suppressMessages(suppressWarnings(library(rjson)))
suppressMessages(suppressWarnings(library(ggplot2)))
suppressMessages(suppressWarnings(library(jsonlite)))
suppressMessages(suppressWarnings(library(stringr)))
suppressMessages(suppressWarnings(library(tidyr)))
suppressMessages(suppressWarnings(library(dplyr)))
suppressMessages(suppressWarnings(library(devtools)))
```

```{r}
murl1<- fromJSON("http://api.nytimes.com/svc/movies/v2/reviews/search.json?opening-date=2016-01-01;2016-04-28&api-key=ef056a1d0cdde8b2f03c95bc7dd57722:19:29126896")

murl2<- fromJSON("http://api.nytimes.com/svc/movies/v2/reviews/search.json?opening-date=2016-01-01;2016-04-28&api-key=ef056a1d0cdde8b2f03c95bc7dd57722:19:29126896&offset=20")


murl3<- fromJSON("http://api.nytimes.com/svc/movies/v2/reviews/search.json?opening-date=2016-01-01;2016-04-28&api-key=ef056a1d0cdde8b2f03c95bc7dd57722:19:29126896&offset=40")

murl1<- murl1$results
murl2<- murl2$results
murl3<- murl3$results

murl1s<- subset(murl1[,c(1,7,8)])
murl2s<- subset(murl2[,c(1,7,8)])
murl3s<- subset(murl3[,c(1,7,8)])

moviesall <- rbind(murl1s, murl2s,murl3s)
moviesall


str(murl1)
murl1

```


